### ISSUE TITLE
Error in bash download.sh step 

### ISSUE THREAD

**Issue by yusufaly** [microsoft/visual-chatgpt#123]
I get the following error when I run bash download.sh on Windows. 

![image](https://user-images.githubusercontent.com/758596/224552906-3c551c38-c120-4953-a924-2b51205c1e08.png)

**Comment by pradeeps** [comment]
Could you let me know a bit more details on your setup?  Are you running this in wsl?

In any case, from the looks of it, you don't git installed. Could you please install it and try to run it again?

**Comment by himomohi** [comment]
"no suchfile or directory"  keep an eye out for

**Comment by semmyk-research** [comment]
Error due to carriage returns (CR, "\r", 0x0d) at the ends of lines in the download.sh shell.

_____________ 
## download the visual foundation models
## Do this in the terminal
# bash download.sh

#### ERROR
vchatgpt/download.sh: line 5: cd: $'ControlNet/models\r': No such file or directory
... ... ...
https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_mlsd.pth%0D
Resolving huggingface.co (huggingface.co)... 52.1.102.136, 52.87.127.254, 54.235.118.239, ...
Connecting to huggingface.co (huggingface.co)|52.1.102.136|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
###

## to resolve the wget 404 error due to the %0D appended to the url
## my fix (assist from https://github.com/microsoft/visual-chatgpt/issues/23)
#tr -d '\r' < download_original.sh > download_rem.sh

## where download_original.sh is the 'dowload.sh' in the bash file provided
## the ',' indicate file to work one
## the '>' indicate file to pipe output to
## 'download_rem.sh' is the output file after stripping off the '\r' | '%0D'

bash download_rem.sh

**Comment by hsmchoi** [comment]
Thx!!

**Comment by Robynwang** [comment]
@yusufaly May I ask if it has been resolved? We have also encountered this situation
