### ISSUE TITLE
I wrote a fork for installing on Windows

### ISSUE THREAD

**Issue by bycloudai** [microsoft/visual-chatgpt#38]
https://github.com/bycloudai/visual-chatgpt-Windows

unfortunately I've gotten:

 `OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 24.00 GiB total
capacity; 23.00 GiB already allocated; 0 bytes free; 23.18 GiB reserved in total by PyTorch)
If reserved memory is >> allocated memory try setting max_split_size_mb to avoid
fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

any suggestions?

Thank you for the great work

**Comment by gillopillo** [comment]
it goes OOM because the standard implementation reaquires almost 70 GB of vram, as you can see in the readme. you need to reduce the number of available models, use multiple gpus, or buy an A100. Another reasonable way to do this would be code that swaps models in and out of vram as necessary instead of gobbling up 70 GB altogether.

**Comment by bycloudai** [comment]
@rupeshs your suggestion works! Thank you.
I will add it to my fork if you don't mind.
